name: Terraform Deploy

on:
  workflow_run:
    workflows: ["CI â€“ Build & Push Docker Image (Docker Hub)"]
    types:
      - completed

permissions:
  actions: read
  contents: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download image tag artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: "ci.yml"
          name: image-tag
          path: .
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Read image tag
        id: image_tag
        run: echo "tag=$(cat image-tag.txt)" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: Terraform5/
        run: terraform init

      - name: Terraform Apply
        working-directory: Terraform5/
        run: |
          terraform apply -auto-approve \
            -var="image_tag=${{ steps.image_tag.outputs.tag }}" \
            -var="ami_id=ami-0d1b5a8c13042c939" \
            -var="key_name=strapii-key" \
            -var="aws_region=us-east-2" \
            -var="instance_type=t2.micro"
